Pipenv introduce
MonolithAILtd/monolith-filemanager pull request #27
Opened 2021-10-11 08:21 UTC by owenwaltonmono

**Task**
https://monolith-ai.atlassian.net/browse/MN-4289 - Move away from using just pip towards using pipenv for dependency management. Ensures reproducible, deterministic builds.

- Have added a modified the test github action to run the tests using the pipenv setup.
- In the setup.py I have included a new helper class `RequirementsManager` which is used to read from the Pipfile any relevant packages and versions which are `install_requires` or `extra_requires` arg values. This should prevent having to maintain the setup.py consistency with the Pipfile in future.

**Tests**
Included a crude functional test for the `RequirementsManager`. This demonstrates the parsing from Pipfile package format to an acceptable List[str] format to pass to the setup.py args.

**Other Notes**
- https://monolith-ai.atlassian.net/l/c/Qr1G9Ug6 this confluence page can acts as a repository of relevant findings from this dependency management investigation. Also contains a section on 'Further Considerations' e.g. how to handle specifying internal git repos as dependencies with pipenv and how might we have to alter our deployment scripts to use pipenv rather than pip.

2021-11-02 16:39 UTC, owenwaltonmono commented on tests/setup/copy_requirements_manager.py
> +class RequirementsManager:
Have duplicated the code from setup.py to here since cannot import from top level file. This file and the corresponding tests will need to be updated when amended in setup.py to ensure tests remain relevant. I appreciate this is not an elegant way to handle this, but was the only way I could think to test the helper class. I am open to alternative suggestions.

2021-11-04 17:12 UTC, TurtleIntercept requested changes
The tests are useful for the RequirementsManager class so may as well use them. Feels like this might have been done before though, have you checked if there's a third party library that handles this?

2021-11-04 17:12 UTC, TurtleIntercept commented on tests/setup/copy_requirements_manager.py
> +class RequirementsManager:
Better way:
Create a folder in MonolithFilemanager called setup:
Place just the RequirementsManager class there
Add the __init__.py

Add
`from monolith_filemanager.setup.RequirementsManager import RequirementsManager`
to both the test and the setup.py. 

Should be able to get rid of the copy and paste.

2021-11-05 05:22 UTC, McPonolith commented on tests/setup/copy_requirements_manager.py
> +class RequirementsManager:
I think this should be its own thing and placed into a gist that includes the class file and it's test.   
I would then comment on the gist, to say its taken from the MFM project. And then in the MFM project copy the file  (Using the setup that @TurtleIntercept suggested) with a link/comment to the gist, to say to keep the two in sync.

2021-11-05 08:05 UTC, McPonolith requested changes
I THINK alot of this could be simplified using ConfigParser.

Heres a real quick (not ready for production, ie the replaces should probably be locked to the start and end etc)
```
#!/usr/bin/env python 

import configparser

config = configparser.ConfigParser()
config.read('./Pipfile.txt')

def simplify_section(section):
    def _simplify_value(key):
        value = eval(section[key].replace("{", "dict(").replace("}", ")"))
        return '%s%s'%(key, section[key].strip('"')) if isinstance(value, str) else '%s[%s]%s' % (key, value['extras'][0], value['version'])
    return list(map(_simplify_value, section))

print(simplify_section(config['packages']))

print(simplify_section(config['dev-packages']))

```

2021-11-05 08:05 UTC, McPonolith commented on setup.py
> +reqs.set_package_dicts()
Why isn't self.reqs.set_package_dicts() part of the constructor, as it always seems to be called after the object is created

2021-11-05 08:05 UTC, McPonolith commented on tests/setup/copy_requirements_manager.py
> +    def parse_complex_pack(self, package_str: str) -> str:
How many of these methods are gonna be publicly exposed, I only see reqs.get_loosened_requirements being used, maybe add _ to the start of the others to make it clear

2021-11-05 08:05 UTC, McPonolith commented on tests/setup/copy_requirements_manager.py
> +            self.pipfile: List[str] = pipfile.read().split("\n")
Use readlines?

2021-11-05 08:05 UTC, McPonolith commented on tests/setup/copy_requirements_manager.py
> +        clean_list = [text.replace('"', '').replace("{", "").replace("}", "") for text in package_str.split(" = ")]
Id be concerned with " = " the exact spacing required for this.

I suspect there's a way to deserialise this, without this. It seems a bit flaky. Even if you have to use the equivalent of eval or whatever

2021-11-05 08:05 UTC, McPonolith commented on tests/setup/copy_requirements_manager.py
> +        return [package for package in self.pipfile[self.package_index + 1:self.dev_package_index - 1] if
What happens if dev packages is listed before normal packages. You should be able to use configparser. And then check if its complex etc by checking if its a string or a dict

2021-11-05 08:05 UTC, McPonolith commented on tests/setup/copy_requirements_manager.py
> +        if self.simple_package_dict != {}:
Maybe best to have if self.simple_package_dict == {}: return None
To be clear about your intentions

2021-11-05 08:05 UTC, McPonolith commented on tests/setup/copy_requirements_manager.py
> +    def __init__(self, pipfile_loc: str):
Maybe provide a sensible default for pipfile_loc ??? Maybe :)

2021-11-05 08:05 UTC, McPonolith commented on tests/setup/copy_requirements_manager.py
> +    def get_loosened_requirements(self, filter: List[str] = None) -> List[str]:
I feel like filter needs renamed, Id be expecting to pass a function to it

2021-11-05 08:27 UTC, owenwaltonmono commented on README.md
> +and generate a successfully .lock file before pushing.
changed

2021-11-05 08:30 UTC, owenwaltonmono commented on setup.py
> +reqs.set_package_dicts()
Have moved into constructor, sometimes hesitant to call methods in constructor, but tbh it's just a bad habit

2021-11-05 08:31 UTC, owenwaltonmono commented on tests/setup/copy_requirements_manager.py
> +    def parse_complex_pack(self, package_str: str) -> str:
Will update private/public method syntax

2021-11-05 08:40 UTC, owenwaltonmono commented on tests/setup/copy_requirements_manager.py
> +        clean_list = [text.replace('"', '').replace("{", "").replace("}", "") for text in package_str.split(" = ")]
Agreed, not super happy with all this suspect string manipulation. I will investigate some 3rd party toml config parsers.

2021-11-05 08:41 UTC, owenwaltonmono commented on tests/setup/copy_requirements_manager.py
> +    def get_loosened_requirements(self, filter: List[str] = None) -> List[str]:
yeah, poor naming convention :(

2021-11-05 08:44 UTC, owenwaltonmono commented on tests/setup/copy_requirements_manager.py
> +class RequirementsManager:
I'm going to investigate modifying this to use a 3rd party toml configparser and try to set up a gist for it. cheers for useful comments

2021-11-05 13:08 UTC, owenwaltonmono commented on setup.py
> +install_requires = [pack.split(">=")[0] for pack in reqs.get_loosened_requirements() if pack not in extra_packs]
Have refactored to incorporate your ConfigParser approach, have amended arg from 'filter' to 'extras_require'

2021-11-05 13:09 UTC, owenwaltonmono commented on tests/setup/copy_requirements_manager.py
> +        if self.simple_package_dict != {}:
Have defaulted packages dicts to None

2021-11-05 13:10 UTC, owenwaltonmono commented on tests/setup/copy_requirements_manager.py
> +    def get_loosened_requirements(self, filter: List[str] = None) -> List[str]:
changed

2021-11-08 10:26 UTC, owenwaltonmono commented on tests/setup/copy_requirements_manager.py
> +class RequirementsManager:
I've updated this to use the built in `configparser` using Emmett's method. Currently this resides in it's own top level package. I misunderstood how setuptools worked originally and did not think that you could access project packages from the `setup.py`

2021-11-08 11:46 UTC, TurtleIntercept approved these changes
Couple of minor changes suggested but happy with overall approach

2021-11-08 11:46 UTC, TurtleIntercept commented on requirements_manager/requirements_manager_class.py
> +        if os.path.exists(pipfile_loc):
Minor: Maybe slightly more readable

```suggestion
    if not os.path.exists(pipfile_loc):
      raise PipfilePathDoesNotExistError()
    self.config: ConfigParser = configparser.ConfigParser()
    self.config.read(pipfile_loc)
```

2021-11-08 11:46 UTC, TurtleIntercept commented on requirements_manager/requirements_manager_class.py
> +    def __init__(self, pipfile_loc: str) -> None:
I like @McPonolith's idea of giving this a sensible default

2021-11-08 12:07 UTC, owenwaltonmono commented on requirements_manager/requirements_manager_class.py
> +    def __init__(self, pipfile_loc: str) -> None:
Have defaulted to "./Pipfile" and added a new MANIFEST.in with the `requirements_manager` package and the `Pipfile` to include in the source distribution

2021-11-08 12:12 UTC, merged